[package]
edition = "2021"
name = "test-hash-napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
sha2 = "0.9.8"
rand = "0.8.4"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
